//------------CUSTOMER---------------------
export const FIND_ALL_CUSTOMER = "FIND_ALL_CUSTOMER"
export const FIND_ALL_CUSTOMER_SUCCESS = "FIND_ALL_CUSTOMER_SUCCESS"
export const FIND_ALL_CUSTOMER_FAILURE = "FIND_ALL_CUSTOMER_FAILURE"

export const SAVE_CUSTOMER = "SAVE_CUSTOMER"
export const SAVE_CUSTOMER_SUCCESS = "SAVE_CUSTOMER_SUCCESS"
export const SAVE_CUSTOMER_FAILURE = "SAVE_CUSTOMER_FAILURE"

export const FIND_CUSTOMER_BY_ID = "FIND_CUSTOMER_BY_ID"
export const FIND_CUSTOMER_BY_ID_SUCCESS = "FIND_CUSTOMER_BY_ID_SUCCESS"
export const FIND_CUSTOMER_BY_ID_FAILURE = "FIND_CUSTOMER_BY_ID_FAILURE"

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE"

//------------TRANSACTION-------------------

export const FIND_ALL_TRANSACTION = "FIND_ALL_TRANSACTION"
export const FIND_ALL_TRANSACTION_SUCCESS = "FIND_ALL_TRANSACTION_SUCCESS"
export const FIND_ALL_TRANSACTION_FAILURE = "FIND_ALL_TRANSACTION_FAILURE"

export const SAVE_TRANSACTION = "SAVE_TRANSACTION"
export const SAVE_TRANSACTION_SUCCESS = "SAVE_TRANSACTION_SUCCESS"
export const SAVE_TRANSACTION_FAILURE = "SAVE_TRANSACTION_FAILURE"

export const FIND_TRANSACTION_BY_ID = "FIND_TRANSACTION_BY_ID"
export const FIND_TRANSACTION_BY_ID_SUCCESS = "FIND_TRANSACTION_BY_ID_SUCCESS"
export const FIND_TRANSACTION_BY_ID_FAILURE = "FIND_TRANSACTION_BY_ID_FAILURE"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS"
export const UPDATE_TRANSACTION_FAILURE = "UPDATE_TRANSACTION_FAILURE"

// ------------------LOGIN------------------------------------

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

//-----------------------SIGN UP--------------------------------

export const FIND_ALL_ACCOUNT = "FIND_ALL_ACCOUNT"
export const FIND_ALL_ACCOUNT_SUCCESS = "FIND_ALL_ACCOUNT_SUCCESS"
export const FIND_ALL_ACCOUNT_FAILURE = "FIND_ALL_ACCOUNT_FAILURE"

export const SAVE_ACCOUNT = "SAVE_ACCOUNT"
export const SAVE_ACCOUNT_SUCCESS = "SAVE_ACCOUNT_SUCCESS"
export const SAVE_ACCOUNT_FAILURE = "SAVE_ACCOUNT_FAILURE"

export const FIND_ACCOUNT_BY_ID = "FIND_ACCOUNT_BY_ID"
export const FIND_ACCOUNT_BY_ID_SUCCESS = "FIND_ACCOUNT_BY_ID_SUCCESS"
export const FIND_ACCOUNT_BY_ID_FAILURE = "FIND_ACCOUNT_BY_ID_FAILURE"

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS"
export const UPDATE_ACCOUNT_FAILURE = "UPDATE_ACCOUNT_FAILURE"

export const REMOVE_ACCOUNT_BY_ID = "REMOVE_ACCOUNT_BY_ID"
export const REMOVE_ACCOUNT_BY_ID_SUCCESS = "REMOVE_ACCOUNT_BY_ID_SUCCESS"
export const REMOVE_ACCOUNT_BY_ID_FAILURE = "REMOVE_ACCOUNT_BY_ID_FAILURE"

//---------------------REPORT------------------------------------------
export const FIND_ALL_REPORT = "FIND_ALL_REPORT"
export const FIND_ALL_REPORT_SUCCESS = "FIND_ALL_REPORT_SUCCESS"
export const FIND_ALL_REPORT_FAILURE = " FIND_ALL_REPORT_FAILURE"